server:
  port: 8081

spring:
  redis:
    #database: 0
    host: localhost
    port: 6379
    password:
    timeout: 30000
    connect-timeout: 5000
    #lettuce:
    #  pool:
    #    max-active: 8
    #    max-wait: -1
    #    max-idle: 8
    #    min-idle: 0


