server:
  port: 8082


spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.0.60:1521:RJHQ
    username: userwx
    password: Jnby@wxdb2017
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  type-aliases-package: com.jdi.oracle.*.entity
  mapper-locations: classpath:mapper/*.xml
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl